version: '3.8'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    platform: linux/amd64
    env_file:
      - csvserver.env
    ports:
      - "9393:9300"
    volumes:
      - /Users/avinash.malakar/Downloads/csvserver/inputdata:/csvserver/inputdata
