 version: '3.8'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    platform: linux/amd64
    env_file:
      - csvserver.env
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    volumes:
      - /Users/avinash.malakar/Downloads/csvserver/solution/prometheus.yml:/etc/prometheus/prometheus.yml

